const ansi = require("./ansi-string.js");
console.log(ansi.red("You can make red like this"));
console.log(ansi.yellow`You can make red with tagged template string also`);
console.log("You can make", ansi.green("inline green"), "like this");
ansi.yellow.stdout();
console.log("You can make block of colored text");
console.log("like this.");
console.log("line 1");
console.log("line 2");
console.log("line 3");
ansi.reset.stdout();
console.log("Not it's normal text again");
